#!/bin/sh
#
# sshd        Starts sshd.
#

# Make sure the ssh-keygen progam exists
[ -f /cheri/usr/bin/ssh-keygen ] || exit 0

umask 077

start() {
	# Create any missing keys
	printf "Generating CHERI ssh keys\n"
	/cheri/usr/bin/ssh-keygen -A

	printf "Starting CHERI sshd: "
	/cheri/usr/sbin/sshd
	touch /var/lock/sshd-cheri
	echo "OK"
}
stop() {
	printf "Stopping CHERI sshd: "
	killall sshd
	rm -f /var/lock/sshd-cheri
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

